### ISSUE TITLE
JelloSwift for MindMap is it possible?

### ISSUE THREAD

**Issue by serbuk** [LuizZak/JelloSwift#7]
Great library! Can it be used to build a tree layout for a "dynamic" mind map UI? Our requirement is that the nodes are draggable. When the user drags one node positions of the rest nodes should adapt to the change.

Soft-body physics is nice for "gamification" of the app.

**Comment by LuizZak** [comment]
I'm thinking it could be done, JelloSwift has support for [whole-body constraining](https://github.com/LuizZak/JelloSwift/blob/master/Sources/BodyJointLink.swift), and it should be trivial do use a [`PressureComponent`](https://github.com/LuizZak/JelloSwift/blob/master/Sources/PressureComponent.swift) along with some internal springs on nodes to keep them from collapsing. Collisions between linked bodies can be enabled to allow for non-overlapping behavior. Playing around with the RestDistance of each constraint could allow for springy behavior only when nodes get too close or too far from each other.

Depending on the number of nodes, the simulation could get unstable and bodies could fling everywhere, but tuning [Body.velDaping](https://github.com/LuizZak/JelloSwift/blob/master/Sources/Body.swift#L54) property could alleviate some of that.

**Comment by serbuk** [comment]
Thank you for the reply!
